CUDA_VISIBLE_DEVICES=7  python 3_run_inference_trace.py --exp_name exp024 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset VisuRiddles   --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp024_VisuRiddles.out 2>&1
CUDA_VISIBLE_DEVICES=7  python 3_run_inference_trace.py --exp_name exp024 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset RAVEN         --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp024_RAVEN.out 2>&1
CUDA_VISIBLE_DEVICES=7  python 3_run_inference_trace.py --exp_name exp024 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset MARVEL        --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp024_MARVEL.out 2>&1
CUDA_VISIBLE_DEVICES=7  python 3_run_inference_trace.py --exp_name exp024 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset LogicVista    --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp024_LogicVista.out 2>&1
CUDA_VISIBLE_DEVICES=7  python 3_run_inference_trace.py --exp_name exp024 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset PuzzleVQA     --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp024_PuzzleVQA.out 2>&1
CUDA_VISIBLE_DEVICES=7  python 3_run_inference_trace.py --exp_name exp024 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset AlgoPuzzleVQA --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp024_AlgoPuzzleVQA.out 2>&1

CUDA_VISIBLE_DEVICES=7  python 3_run_inference_trace.py --exp_name exp023 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset VisuRiddles   --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp023_VisuRiddles.out 2>&1
CUDA_VISIBLE_DEVICES=7  python 3_run_inference_trace.py --exp_name exp023 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset RAVEN         --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp023_RAVEN.out 2>&1
CUDA_VISIBLE_DEVICES=7  python 3_run_inference_trace.py --exp_name exp023 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset MARVEL        --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp023_MARVEL.out 2>&1
CUDA_VISIBLE_DEVICES=7  python 3_run_inference_trace.py --exp_name exp023 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset LogicVista    --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp023_LogicVista.out 2>&1
CUDA_VISIBLE_DEVICES=7  python 3_run_inference_trace.py --exp_name exp023 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset PuzzleVQA     --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp023_PuzzleVQA.out 2>&1
CUDA_VISIBLE_DEVICES=7  python 3_run_inference_trace.py --exp_name exp023 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset AlgoPuzzleVQA --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp023_AlgoPuzzleVQA.out 2>&1