# CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp043 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset VisuRiddles   --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp043_VisuRiddles.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp043 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset RAVEN         --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp043_RAVEN.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp043 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset MARVEL        --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp043_MARVEL.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp043 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset LogicVista    --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp043_LogicVista.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp043 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset PuzzleVQA     --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp043_PuzzleVQA.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp043 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset AlgoPuzzleVQA --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp043_AlgoPuzzleVQA.out 2>&1

# # CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp044 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset VisuRiddles   --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp044_VisuRiddles.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp044 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset RAVEN         --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp044_RAVEN.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp044 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset MARVEL        --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp044_MARVEL.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp044 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset LogicVista    --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp044_LogicVista.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp044 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset PuzzleVQA     --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp044_PuzzleVQA.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp044 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset AlgoPuzzleVQA --use_attention_guidance true  --dla_entropy_threshold -10 --use_context_aware false   > exp044_AlgoPuzzleVQA.out 2>&1