CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp028 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset VisuRiddles   --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp028_VisuRiddles.out 2>&1
CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp028 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset RAVEN         --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp028_RAVEN.out 2>&1
CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp028 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset MARVEL        --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp028_MARVEL.out 2>&1
CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp028 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset LogicVista    --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp028_LogicVista.out 2>&1
CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp028 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset PuzzleVQA     --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp028_PuzzleVQA.out 2>&1
CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp028 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset AlgoPuzzleVQA --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp028_AlgoPuzzleVQA.out 2>&1

CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp027 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset VisuRiddles   --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp027_VisuRiddles.out 2>&1
CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp027 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset RAVEN         --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp027_RAVEN.out 2>&1
CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp027 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset MARVEL        --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp027_MARVEL.out 2>&1
CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp027 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset LogicVista    --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp027_LogicVista.out 2>&1
CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp027 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset PuzzleVQA     --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp027_PuzzleVQA.out 2>&1
CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp027 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset AlgoPuzzleVQA --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp027_AlgoPuzzleVQA.out 2>&1

