# CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp047 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset VisuRiddles   --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp047_VisuRiddles.out 2>&1
# CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp047 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset RAVEN         --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp047_RAVEN.out 2>&1
# CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp047 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset MARVEL        --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp047_MARVEL.out 2>&1
# CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp047 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset LogicVista    --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp047_LogicVista.out 2>&1
# CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp047 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset PuzzleVQA     --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp047_PuzzleVQA.out 2>&1
CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp047 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset AlgoPuzzleVQA --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp047_AlgoPuzzleVQA.out 2>&1

# CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp048 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset VisuRiddles   --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp048_VisuRiddles.out 2>&1
# CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp048 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset RAVEN         --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp048_RAVEN.out 2>&1
# CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp048 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset MARVEL        --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp048_MARVEL.out 2>&1
# CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp048 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset LogicVista    --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp048_LogicVista.out 2>&1
# CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp048 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset PuzzleVQA     --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp048_PuzzleVQA.out 2>&1
# CUDA_VISIBLE_DEVICES=1  python 3_run_inference_trace.py --exp_name exp048 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset AlgoPuzzleVQA --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware false   > exp048_AlgoPuzzleVQA.out 2>&1