CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp026 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset VisuRiddles   --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp026_VisuRiddles.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp026 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset RAVEN         --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp026_RAVEN.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp026 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset MARVEL        --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp026_MARVEL.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp026 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset LogicVista    --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp026_LogicVista.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp026 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset PuzzleVQA     --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp026_PuzzleVQA.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp026 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Instruct --dataset AlgoPuzzleVQA --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp026_AlgoPuzzleVQA.out 2>&1

CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp025 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset VisuRiddles   --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp025_VisuRiddles.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp025 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset RAVEN         --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp025_RAVEN.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp025 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset MARVEL        --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp025_MARVEL.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp025 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset LogicVista    --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp025_LogicVista.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp025 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset PuzzleVQA     --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp025_PuzzleVQA.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp025 --model_path /data/public/model/Qwen/Qwen3-VL-2B-Thinking --dataset AlgoPuzzleVQA --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp025_AlgoPuzzleVQA.out 2>&1

