# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp045 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset VisuRiddles   --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp045_VisuRiddles.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp045 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset RAVEN         --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp045_RAVEN.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp045 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset MARVEL        --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp045_MARVEL.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp045 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset LogicVista    --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp045_LogicVista.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp045 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset PuzzleVQA     --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp045_PuzzleVQA.out 2>&1
CUDA_VISIBLE_DEVICES=6  python 3_run_inference_trace.py --exp_name exp045 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Thinking --dataset AlgoPuzzleVQA --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp045_AlgoPuzzleVQA.out 2>&1

# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp046 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset VisuRiddles   --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp046_VisuRiddles.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp046 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset RAVEN         --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp046_RAVEN.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp046 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset MARVEL        --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp046_MARVEL.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp046 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset LogicVista    --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp046_LogicVista.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp046 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset PuzzleVQA     --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp046_PuzzleVQA.out 2>&1
# CUDA_VISIBLE_DEVICES=0  python 3_run_inference_trace.py --exp_name exp046 --model_path /data/public/model/Qwen/Qwen3-VL-4B-Instruct --dataset AlgoPuzzleVQA --use_attention_guidance true  --dla_entropy_threshold 1.27 --use_context_aware true --ctx_entropy_threshold 1.27   > exp046_AlgoPuzzleVQA.out 2>&1